services:
  tune-recog:
    build:
      context: ./app  # Build context for the Dockerfile
      dockerfile: Dockerfile  # Path to the Dockerfile
    runtime: nvidia
    shm_size: '10gb'
    stdin_open: true
    tty: true
    container_name: tune-recog-corti
    volumes:
      - ${RESOURCES_PATH}:/resources
      - .:/app
    env_file:
      - .env  # Environment file containing environment variables
    environment:
      - PYTHONUNBUFFERED=1  # Disables Python output buffering to get real-time logs
      - CUDA_VISIBLE_DEVICES=1,2  # Specifies the GPU devices visible to the container
    ports:
      - "1234:1234"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]