version: "3.8"
services:
  tune-sis-recomender:
    build:
      context: .  # Directorio de construcción
      dockerfile: Dockerfile
    gpus:
      - driver: nvidia
        count: all
        capabilities: ["gpu"]
    stdin_open: true
    tty: true
    container_name: tune-sis-recomender
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1  # Log en tiempo real
      - CUDA_VISIBLE_DEVICES=0  # GPU que se quiere usar
    ports:
      - "1234:1234"
    mem_limit: 24g       # límite máximo de RAM
    mem_reservation: 16g # reserva de RAM garantizada
    cpus: "8.0"          # núcleos de CPU dedicados
    shm_size: "8g"